# Generated by Django 4.0.6 on 2022-08-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='Name',
            new_name='role',
        ),
    ]
